# Generated by Django 3.2.5 on 2022-12-13 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioning', '0003_profile_newusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rquestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=4096)),
                ('answer', models.CharField(max_length=4096)),
                ('productid', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.ManyToManyField(blank=True, through='auctioning.Rquestion', to=settings.AUTH_USER_MODEL),
        ),
    ]
