# Generated by Django 3.2.5 on 2022-12-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioning', '0004_auto_20221213_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='winbid',
            field=models.CharField(default='No bids', max_length=100),
        ),
    ]
