# Generated by Django 3.2.5 on 2022-12-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctioning', '0005_product_winbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='question',
            new_name='rquestion',
        ),
    ]
