# Generated by Django 4.1.2 on 2022-12-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioning', '0007_alter_user_rquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=245, null=True),
        ),
        migrations.AlterField(
            model_name='rquestion',
            name='answer',
            field=models.CharField(default='No answer', max_length=4096),
        ),
    ]
