# Generated by Django 4.1.2 on 2022-12-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioning', '0008_alter_profile_email_alter_rquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
