# Generated by Django 4.1.2 on 2022-12-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioning', '0009_alter_profile_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='proimage',
            field=models.ImageField(default='images/profile.jpg', upload_to='images'),
        ),
    ]
