# Generated by Django 4.1.2 on 2022-12-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctioning', '0010_alter_profile_proimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='proimage',
            field=models.ImageField(default='images/profile.png', upload_to='images'),
        ),
    ]
